org: ${env:ORG_NAME}
service: ${env:USERS_SERVICE_NAME}

plugins:
  - serverless-dotenv-plugin

custom:
  ordersStack: ${env:ORDERS_SERVICE_NAME}-${self:provider.stage}

provider:
  name: aws
  runtime: python3.13
  memorySize: 256
  stage: dev
  region: us-east-1
  timeout: 20

  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:ROLE_NAME}

  environment:
    USERS_TABLE: ${self:service}-${self:provider.stage}-UsersTable
    JWT_SECRET: ${env:JWT_SECRET}

    EVENT_BUS_NAME: ${cf:${self:custom.ordersStack}.EventBusName}
    ORDERS_TABLE_NAME: ${cf:${self:custom.ordersStack}.OrdersTableName}
    DELIVERY_BUCKET_NAME: ${cf:${self:custom.ordersStack}.DeliveryBucketName}

functions:
  CreateUser:
    handler: CreateUser.lambda_handler
    events:
      - http:
          path: /users
          method: post
          cors: true  

  Login:
    handler: Login.lambda_handler
    events:
      - http:
          path: /auth/login
          method: post
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-UsersTable
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: user_id
            AttributeType: S
          - AttributeName: correo
            AttributeType: S
          - AttributeName: dni
            AttributeType: S

        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: user_id
            KeyType: RANGE

        GlobalSecondaryIndexes:
          - IndexName: CorreoIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: correo
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

          - IndexName: DniIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: dni
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

  Outputs:
    UsersTableName:
      Value: !Ref UsersTable
      Export:
        Name: ${self:service}-${self:provider.stage}-UsersTableName
