org: ${env:ORG_NAME}
service: ${env:PRODUCTS_SERVICE_NAME}

plugins:
  - serverless-dotenv-plugin

custom:
  ordersStack: ${env:ORDERS_SERVICE_NAME}-${self:provider.stage}

provider:
  name: aws
  runtime: python3.13
  memorySize: 256
  stage: dev
  region: us-east-1
  timeout: 20

  iam:
    role: arn:aws:iam::${env:AWS_ACCOUNT_ID}:role/${env:ROLE_NAME}

  environment:
    PRODUCTS_TABLE: ${self:service}-${self:provider.stage}-ProductsTable
    IMAGES_BUCKET: ${self:service}-${self:provider.stage}-product-images

functions:
  # GET /products - Listar todos los productos
  GetProducts:
    handler: GetProducts.lambda_handler
    events:
      - http:
          path: /products
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - x-tenant-id
            allowCredentials: false


  Upload_image:
    handler: Upload_image.lambda_handler
    events:
      - http:
          path: /upload-url
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - x-tenant-id
            allowCredentials: false

  # GET /products/{product_id} - Obtener un producto
  GetProductById:
    handler: GetProductById.lambda_handler
    events:
      - http:
          path: /products/{product_id}
          method: get
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - x-tenant-id
            allowCredentials: false

  # POST /products - Crear producto (ADMIN)
  CreateProduct:
    handler: CreateProduct.lambda_handler
    events:
      - http:
          path: /products
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - x-tenant-id
            allowCredentials: false

  # PUT /products/{product_id} - Actualizar producto (ADMIN)
  UpdateProduct:
    handler: UpdateProduct.lambda_handler
    events:
      - http:
          path: /products/{product_id}
          method: put
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - x-tenant-id
            allowCredentials: false

  # DELETE /products/{product_id} - Eliminar producto (ADMIN)
  DeleteProduct:
    handler: DeleteProduct.lambda_handler
    events:
      - http:
          path: /products/{product_id}
          method: delete
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - x-tenant-id
            allowCredentials: false

resources:
  Resources:
    ProductImagesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:service}-${self:provider.stage}-product-images
        CorsConfiguration:
          CorsRules:
            - AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
                - PUT
                - POST
                - HEAD
              MaxAge: 3000
              ExposedHeaders:
                - ETag
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    
    ProductImagesBucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref ProductImagesBucket
        PolicyDocument:
          Statement:
            - Effect: Allow
              Principal: '*'
              Action:
                - s3:GetObject
              Resource: !Sub '${ProductImagesBucket.Arn}/*'
    ProductsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-ProductsTable
        BillingMode: PAY_PER_REQUEST

        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: product_id
            AttributeType: S
          - AttributeName: category
            AttributeType: S
          - AttributeName: created_at
            AttributeType: S

        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: product_id
            KeyType: RANGE

        GlobalSecondaryIndexes:
          # Buscar por categoría
          - IndexName: CategoryIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: category
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

          # Ordenar por fecha de creación
          - IndexName: CreatedAtIndex
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: created_at
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

  Outputs:
    ProductsTableName:
      Value: !Ref ProductsTable
      Export:
        Name: ${self:service}-${self:provider.stage}-ProductsTableName